### ISSUE TITLE
Internal error occurred while attempting to perform this command

### ISSUE THREAD

**Issue by Deflexz** [JEFF-Media-GbR/Spigot-InvUnload#3]
Uploaded plugin
Restarted server
Joined server
/unload command used. 
Internal error occurred while attempting to perform this command

Console Dump has been attached
[dump.txt](https://github.com/JEFF-Media-GbR/Spigot-InvUnload/files/2560693/dump.txt)

**Comment by Deflexz** [comment]
Reading the dump.txt i notice it calls something from worldguard. 
I guess this is a dependency??? 
com.sk89q.worldguard.WorldGuard

**Comment by mfnalex** [comment]
It softdepends on WorldGuard. You do not have to use it. I will have a look at this later this day :)

**Comment by Deflexz** [comment]
Will be looking forward since I don't like messy inventories. Have a great day :)

**Comment by mfnalex** [comment]
I will answer you again in 3-4 hours, please standby :)

**Comment by Deflexz** [comment]
Take your time. I'm going to sleep .

**Comment by mfnalex** [comment]
Thanks, I think I have fixed it. I will test it a while and then update the resource.

**Comment by mfnalex** [comment]
Fixed, please update to InvUnload 2.0.2
