### ISSUE TITLE
add support update

### ISSUE THREAD

**Issue by successed** [JEFF-Media-GbR/Spigot-InvUnload#4]
add griefprevention support please...

**Comment by mfnalex** [comment]
I can do this if there would be information about the API. Unfortunately, that is all I found: https://github.com/MinecraftPortCentral/GriefPrevention/wiki/API

**Comment by successed** [comment]
> I can do this if there would be information about the API. Unfortunately, that is all I found: https://github.com/MinecraftPortCentral/GriefPrevention/wiki/API

only the owner of the field should be allowed to use that command.

**Comment by successed** [comment]
i have skript:
on right click on sign:
    if region at location of clicked block is set:
        if player is not a member of region at location of clicked block:
            cancel event
            send "&cOnly usable claim owners."

**Comment by mfnalex** [comment]
The plugin is written in Java

**Comment by successed** [comment]
> The plugin is written in Java

i now, I wrote it so you could get samples.

**Comment by mfnalex** [comment]
What I need is a method within the GriefPrevention API to check if a block is inside a region and if that region belongs to a specific player. I could not find this method in the documentation, so I cannot do much right now. Do you know any open source plugins that use the GriefPrevention API? I could then examine the source code.

**Comment by mfnalex** [comment]
Noone has answered my issue so far: https://github.com/MinecraftPortCentral/GriefPrevention/issues/832

**Comment by mfnalex** [comment]
This is still on my todo list, but I don‘t have time right now. Sorry for the inconvenience

**Comment by mfnalex** [comment]
Fixed in 3.0.0 release which is in another repo: https://github.com/JEFF-Media-GbR/Spigot-InvUnloadPlus
