### ISSUE TITLE
Use your own ChestSort API in InvUnload

### ISSUE THREAD

**Issue by Azzurite** [JEFF-Media-GbR/Spigot-InvUnload#5]
I've been using ChestSort and from there stumbled upon this plugin.

I was very confused as I noticed that whatever I unloaded was not being sorted.

Please add running a ChestSort on all chests where items were deposited to!

**Comment by mfnalex** [comment]
InvUnload has been around way before the API was released. I might add this in the future, however I do not have time right now. Feel free to create a pull request :)
