### ISSUE TITLE
1.14.x Both commands preform same action

### ISSUE THREAD

**Issue by Bilibox** [JEFF-Media-GbR/Spigot-InvUnload#7]
/unload & /dump both remove all items (Including your hotbar)

Instead /dump should ignore the hotbar and only dump the inventory into chests.

**Comment by mfnalex** [comment]
I will have a look at this, thank you

**Comment by mfnalex** [comment]
Fixed in 3.0.0 release which is in another repo: https://github.com/JEFF-Media-GbR/Spigot-InvUnloadPlus
