### ISSUE TITLE
Not unloading in barrels.

### ISSUE THREAD

**Issue by maxsupermanhd** [JEFF-Media-GbR/Spigot-InvUnload#9]
/unload not working with barrels in 1.15.2 spigot.

**Comment by SafeguardSanakan** [comment]
Doesn't work in 1.14.4 either. I don't think barrels are included in the unload code.

**Comment by maxsupermanhd** [comment]
I've actually did some work on this after posting it here and no result. There is tons and tons of places where chests are hardcoded and used in only-chest way...

**Comment by mfnalex** [comment]
Thanks, I will add this to my todo list.

**Comment by mfnalex** [comment]
Since the source code is a complete mess, I will probably rewrite the entire plugin. So, this is the time to express major feature requests!

**Comment by mfnalex** [comment]
Fixed in version 3.0.0 which is in another repo: https://github.com/JEFF-Media-GbR/Spigot-InvUnloadPlus
